package gui;


import brauhaus.BrauhausInfo;
import brauhaus.IBrauKessel;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marian
 */
public class GStandardSteuerFenster extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form GSteuerFenster
     */
    public GStandardSteuerFenster(IBrauKessel braukessel) {
        initComponents();
        if(braukessel ==  null)
            throw new NullPointerException("braukessel");
        this.braukessel = braukessel;         
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTemperatur = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblRuehrwerk = new javax.swing.JLabel();
        lblHeizwerk = new javax.swing.JLabel();
        btnRuehrwerk = new javax.swing.JButton();
        btnHeizwerk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Temperatur in °C: ");

        lblTemperatur.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblTemperatur.setText("jLabel2");
        lblTemperatur.setName("lblTemperatur"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Status Rührwerk:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Status Heizwerk:");

        lblRuehrwerk.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblRuehrwerk.setText("jLabel2");
        lblRuehrwerk.setName("lblTemperatur"); // NOI18N

        lblHeizwerk.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblHeizwerk.setText("jLabel2");
        lblHeizwerk.setName("lblTemperatur"); // NOI18N

        btnRuehrwerk.setText("Rührwerk");
        btnRuehrwerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRuehrwerkActionPerformed(evt);
            }
        });

        btnHeizwerk.setText("Heizwerk");
        btnHeizwerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeizwerkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRuehrwerk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(lblTemperatur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39)
                        .addComponent(lblHeizwerk, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addComponent(lblRuehrwerk, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnHeizwerk, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTemperatur))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblHeizwerk))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblRuehrwerk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnRuehrwerk)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(135, Short.MAX_VALUE)
                    .addComponent(btnHeizwerk)
                    .addGap(49, 49, 49)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRuehrwerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRuehrwerkActionPerformed
        boolean status = !braukessel.GetInfo().isRuehrwerkAn();
        this.braukessel.SetRuehwerkStatus(status);
        try {
            setObjekt(braukessel.GetInfo());
        } catch (Exception ex) {
            Logger.getLogger(GStandardSteuerFenster.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRuehrwerkActionPerformed

    private void btnHeizwerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeizwerkActionPerformed
        boolean status = !braukessel.GetInfo().isHeizWerkAn();
        this.braukessel.SetHeizwerkStatus(status);
        try {
            setObjekt(braukessel.GetInfo());
        } catch (Exception ex) {
            Logger.getLogger(GStandardSteuerFenster.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHeizwerkActionPerformed

    @Override
    public void update(Observable o, Object arg) 
    {
        if(!(arg instanceof BrauhausInfo))
        {
            try {
                throw new Exception("Nicht das richtige Objekt");
            } catch (Exception ex) {
                Logger.getLogger(GStandardSteuerFenster.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                
        try {   
            setObjekt((BrauhausInfo)arg);
        } catch (Exception ex) {
            Logger.getLogger(GStandardSteuerFenster.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setObjekt(BrauhausInfo brauhausInfo) throws Exception {
        lblTemperatur.setText(String.valueOf(brauhausInfo.getTemp()));
        if(brauhausInfo.isHeizWerkAn())
            lblHeizwerk.setText("An");
        else
            lblHeizwerk.setText("Aus");
        
        if(brauhausInfo.isRuehrwerkAn())
            lblRuehrwerk.setText("An");
        else
            lblRuehrwerk.setText("Aus");
        this.repaint();
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHeizwerk;
    private javax.swing.JButton btnRuehrwerk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblHeizwerk;
    private javax.swing.JLabel lblRuehrwerk;
    private javax.swing.JLabel lblTemperatur;
    // End of variables declaration//GEN-END:variables

    private IBrauKessel braukessel;

    
}
